[target.wasm32-unknown-unknown]
runner = "wasm-bindgen-test-runner"
#rustflags = ["-C", "target-feature=+simd128"]
#rustflags = ["-C", "link-arg=-zstack-size=8192"]
#rustflags = ["-C", "link-arg=-zstack-size=16384"]
[target.wasm32-wasi]
#rustflags = ["-C", "target-feature=+simd128"]
#[build]
#target = "wasm32-wasip1"
